import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { signOut } from 'next-auth/react'
import { getSession } from 'next-auth/react'
import { NextPageContext } from 'next'
import { useCurrentUser } from '@/hooks/currentUser'

const inter = Inter({ subsets: ['latin'] })

export const getServerSideProps = async (context: NextPageContext) => {
  const session = await getSession(context)
  if (!session) {
    return {
      redirect: {
        destination: '/auth',
        permanent: false,
      },
    }
  }
  return {
    props: {
    },
  }
}

export default function Home() {
  const { data:user } = useCurrentUser()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <button
          className='text-white'
          onClick={() => signOut()}>Sign Out</button>
        <h1 className='text-4xl font-bold text-white'>Hello {user?.email}</h1>
        
      </main>
    </>
  )
}

