import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { signOut } from 'next-auth/react'
import { getSession } from 'next-auth/react'
import { NextPageContext } from 'next'
import { useCurrentUser } from '@/hooks/currentUser'
import Navbar from '@/components/Navbar'
import Billboard from '@/components/Billboard'
import MovieList from '@/components/MovieList'
import useMoviesList from '@/hooks/useMovieList'
import useFavorites from '@/hooks/useFavorites'
import InfoModal from '@/components/InfoModal'
import useInfoModalStore from '@/hooks/useInfoModalStore';
const inter = Inter({ subsets: ['latin'] })


export const getServerSideProps = async (context: NextPageContext) => {
  const session = await getSession(context)
  if (!session) {
    return {
      redirect: {
        destination: '/auth',
        permanent: false,
      },
    }
  }
  return {
    props: {
    },
  }
}

export default function Home() {
  const { data: movies = [] } = useMoviesList();
  const { data: favorites = [] } = useFavorites();

  const { isOpen, closeModal } = useInfoModalStore();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InfoModal visible={isOpen} onClose={closeModal} />

      <Navbar />
      <Billboard />
      <div className="pb-40 flex flex-col gap-28">
        <MovieList title="Trending Now" data={movies} />
        <MovieList title="My List" data={favorites} />
      </div>
    </>
  )
}

